site_name: UK Web Archive Frontend Application Docs
repo_url: https://github.com/nationalarchives/wa-frontend

nav:
  - Home: index.md
  - Dependencies: dependencies.md
  - Structure: structure.md
  - Database: database.md
  - Archive Data Sync: data-sync.md
  - Routes: routes.md
  - Templates: templates.md
